#!/usr/bin/env bash
# Generates lib/shared/build_info.dart from Git metadata and toolchain versions.
# Run from the repository root before every build:
#   bash scripts/generate_build_info.sh
#
# In GitHub Actions add this step before 'flutter build':
#   - name: Generate build info
#     run: bash scripts/generate_build_info.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="$ROOT_DIR/lib/shared/build_info.dart"

# ── Build number ─────────────────────────────────────────────────────────────
# BUILD_NUMBER when the caller set one — scripts/build.sh passes the same
# value it gives `flutter build --build-number`, so the About screen and the
# artifact's versionCode always agree. Otherwise the git commit count.
BUILD_NUMBER_VALUE=${BUILD_NUMBER:-$(git -C "$ROOT_DIR" rev-list --count HEAD 2>/dev/null || echo "0")}

# ── Git info ────────────────────────────────────────────────────────────────
GIT_SHORT=$(git -C "$ROOT_DIR" rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_FULL=$(git -C "$ROOT_DIR" rev-parse HEAD 2>/dev/null || echo "unknown")

# ── Version from pubspec.yaml ────────────────────────────────────────────────
VERSION=$(grep '^version:' "$ROOT_DIR/pubspec.yaml" | sed 's/version: //' | sed 's/+.*//' | tr -d '[:space:]')

# ── Toolchain versions ───────────────────────────────────────────────────────
FLUTTER_VERSION=$(flutter --version 2>&1 | head -1 | awk '{print $2}' || echo "unknown")
# dart --version writes to stderr on some versions, so merge stderr → stdout
DART_VERSION=$(dart --version 2>&1 | awk '{print $4}' || echo "unknown")

# ── Build timestamp ──────────────────────────────────────────────────────────
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ── Write Dart file ──────────────────────────────────────────────────────────
cat > "$OUTPUT" <<EOF
/// Build metadata generated by scripts/generate_build_info.sh.
/// Do not edit manually — regenerate with: bash scripts/generate_build_info.sh
///
/// In CI/CD this file is regenerated before every build.
/// In local development run the script once after cloning.
class BuildInfo {
  BuildInfo._();

  /// Semantic version from pubspec.yaml (e.g. "1.0.0").
  static const String version = '$VERSION';

  /// Build number (e.g. "26") — BUILD_NUMBER when the build set one,
  /// otherwise the git commit count.
  static const String buildNumber = '$BUILD_NUMBER_VALUE';

  /// Short Git commit hash (e.g. "f3c3fd3").
  static const String gitCommit = '$GIT_SHORT';

  /// Full Git commit hash.
  static const String gitCommitFull = '$GIT_FULL';

  /// Flutter SDK version at build time (e.g. "3.29.0").
  static const String flutterVersion = '$FLUTTER_VERSION';

  /// Dart SDK version at build time (e.g. "3.7.0").
  static const String dartVersion = '$DART_VERSION';

  /// ISO-8601 timestamp of the build.
  static const String buildDate = '$BUILD_DATE';

  /// True when compiled in debug mode.
  static const bool isDebug = bool.fromEnvironment('dart.vm.product') == false;
}
EOF

echo "Generated $OUTPUT"
echo "  version:      $VERSION"
echo "  buildNumber:  $BUILD_NUMBER_VALUE"
echo "  gitCommit:    $GIT_SHORT"
echo "  flutterVersion: $FLUTTER_VERSION"
echo "  dartVersion:  $DART_VERSION"
